### ISSUE TITLE
Attachment can be accessed without credentials if filename, formID, UUID, and username are known

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#551]
If a malicious user knows the attachment file name and username for a particular project they are able to access the attachment without requiring credentials. 

This has been reproduced for a specific project on OCHA (see details [here](https://www.flowdock.com/app/kobotoolbox/kobo/threads/_77bfxTnaIHFM_Z3zBUDSAYaqdT)) but not for a separate project on prod. 

This requires knowing the full path used e.g. in the kobocat image gallery:

https://kc.humanitarianresponse.info/attachment/original?media_file=[username]/attachments/[formID]/[UUID]/[filename].jpg

**Comment by jnm** [comment]
I think this is a duplicate of https://github.com/kobotoolbox/kobocat/issues/261, which has been fixed in [release `2.019.16`](https://github.com/kobotoolbox/kpi/releases/tag/2.019.16) and [deployed](https://www.flowdock.com/app/kobotoolbox/kobo/threads/SyLvNLMfggxw5TSOB_D0vrzKS81) (but not yet to OCHA).

**Comment by jnm** [comment]
Confirmed that https://kc.kobotoolbox.org/attachment/original?media_file=jnm_demo/attachments/cd9f1c1f0619416085cb682b60010cc6/bf088518-36a8-420c-b177-29324e4ae5cb/self%20boot-15_8_22.jpg returns `Not shared.` unless I am authenticated and have appropriate access.
