### ISSUE TITLE
superuser can't delete accounts

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#92]
See FD.

**Comment by jnm** [comment]
Looks like this is happening because KC doesn't know about KF's tables that reference `auth_user`:
```
Exception Type: IntegrityError at /admin/auth/user/
Exception Value: update or delete on table "auth_user" violates foreign key constraint "user_id_refs_id_1014a427" on table "koboform_surveydraft"
DETAIL:  Key (id)=(816) is still referenced from table "koboform_surveydraft".
```

**Comment by jnm** [comment]
Proposed solution: https://github.com/kobotoolbox/dkobo/pull/617. The problem, in detail:

* KC and KF both share the same database and make use of the `auth_users` table.
* KC has a variety of other tables with foreign keys to `auth_user`, e.g. `logger_xform`.
* KF also has tables with foreign keys to `auth_user`, e.g. `koboform_surveydraft`.
* Trying to delete a user in KC:
  * Deletes all of the related objects (rows in other tables with foreign keys to that user) that KC knows about; :ok:
  * Tries to delete the user itself (row in `auth_user`) but fails because KF's tables still have rows that reference the user—so the referential integrity check of the database prevents the user from being removed. :x:

What I opted to do was create a new admin action in KF that removes all of a user's related objects but does **not** remove the user itself. After that, deleting the user in KC succeeds, but this means that deleting a user is a two-step process:

1. Go into KF and delete all KF-specific related items for the user;
2. Go into KC and delete the user itself (as well as KC-specific related items, which are removed automatically without an extra command).

This workaround is easily ported to KPI. Maybe in the future the first step could be accomplished with an API call from KC to KF.
